Refactor implicit evaporator to work with HOOMD v5
mphowardlab/azplugins pull request #97
Opened 2024-12-12 15:52 UTC by kkritikak

2024-12-13 02:39 UTC, mphoward reviewed
Thank you Kritika! Here are some comments.

2024-12-13 02:39 UTC, mphoward commented on src/CMakeLists.txt
> +    PlanarMovingHarmonicBarrier.cc
I'm really sorry... looking at these, I realized I made a mess of these names. Could you please rename one more time as:
* `HarmonicBarrier`
* `PlanarHarmonicBarrier`
* `SphericalHarmonicBarrier`

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotential.cc
> +MovingHarmonicPotential::~MovingHarmonicPotential() { };
`;` not needed after function definition.
```suggestion
MovingHarmonicPotential::~MovingHarmonicPotential() { }
```

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotential.cc
> +        && flags[pdata_flag::pressure_tensor])
This is correct! See here:
https://github.com/glotzerlab/hoomd-blue/blob/58b7ba503cadd90cc1ed65f40208a8d2de5b7b63/hoomd/ParticleData.h#L68-L78

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotential.cc
> +                                                                                  py::base<ForceCompute>())
We recently discovered that this way of describing the inheritance of the class leads to very strange (incorrect) behavior in Python, due to some change in pybind11. I think it should be like this instead:
```suggestion
    py::class_<HarmonicBarrier, std::shared_ptr<HarmonicBarrier>, ForceCompute>(m,
                                                                                  "HarmonicBarrier")
```
You will want to propagate this everywhere.

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotential.cc
> +        .def("setParams", &MovingHarmonicPotential::setParams);
To work with the per-type Python interface, I think this is going to need to be modified to accept a data structure for this class that contains all the parameters. That data structure is also going to need a constructor that creates it from a Python dictionary (and I think one that can go the other way too).

Take a look at the methods here for what this class needs as an example:

https://github.com/glotzerlab/hoomd-blue/blob/58b7ba503cadd90cc1ed65f40208a8d2de5b7b63/hoomd/md/PotentialExternal.h#L185

and here for how the parameter class gets implemented:

https://github.com/glotzerlab/hoomd-blue/blob/58b7ba503cadd90cc1ed65f40208a8d2de5b7b63/hoomd/md/EvaluatorExternalMagneticField.h#L48-L76

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotentialGPU.cc
>      m_tuner.reset(new Autotuner(32, 1024, 32, 5, 100000, "implicit_evap", m_exec_conf));
The way that autotuners get created and assigned has changed. See here for an example:

https://github.com/glotzerlab/hoomd-blue/blob/58b7ba503cadd90cc1ed65f40208a8d2de5b7b63/hoomd/md/PotentialExternalGPU.h#L49-L52

The member variable is also going to look different:

https://github.com/glotzerlab/hoomd-blue/blob/58b7ba503cadd90cc1ed65f40208a8d2de5b7b63/hoomd/md/PotentialExternalGPU.h#L39

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotentialGPU.h
>      virtual void setAutotunerParams(bool enable, unsigned int period)
I think this is no longer needed.

2024-12-13 02:39 UTC, mphoward commented on src/PlanarMovingHarmonicBarrierGPU.cu
The boilerplate in the kernel driver functions has changed a bit, please have a look at a file in HOOMD (e.g., in the MPCD folder) for how to update it.

2024-12-13 02:39 UTC, mphoward commented on src/PlanarMovingHarmonicBarrierGPU.cc
The way autotuners are used has changed, take a look in HOOMD source code for an example and update as needed.

2024-12-13 02:39 UTC, mphoward commented on src/MovingHarmonicPotential.h
Do we feel like the cutoff and g parameters are actually useful for us? I don't really use them, so I would be OK if we wanted to remove them in favor of simplicity, going down to just two parameters (spring constant and offset).

2025-01-07 17:56 UTC, kkritikak commented on src/MovingHarmonicPotential.h
I also think it's better to remove them, I also asked Arash and he also said that it's OK  to remove them, currently I haven't removed them but I will remove them soon.

2025-01-07 18:48 UTC, mphoward requested changes
Looks great! Please proceed with removing those two arguments as well as addressing the mostly small comments below. Last thing we need is to port some of them unit tests that validate these objects.

2025-01-07 18:48 UTC, mphoward commented on src/HarmonicBarrier.h
> +        } __attribute__((aligned(16)));
After you remove `g` and `cutoff`, this struct will be the same as a `Scalar2`. That means that it should be aligned to 8 bytes for 32-bit floats and 16 bytes for 64-bit floats. You can do this like in the LJ potential:
https://github.com/glotzerlab/hoomd-blue/blob/f0415ec516c84f203d99d96f226759034683221a/hoomd/md/EvaluatorPairLJ.h#L151-L155

2025-01-07 18:48 UTC, mphoward commented on src/HarmonicBarrier.h
> +    pybind11::dict getParams(std::string type_name)
For completeness, I would like to see this as a Python-specific getter, then also include a C++ getter `getParams` that just returns the actual struct (the complementary method to `setParams`). `getParamsPython` can internally use `getParams` before converting it to a dict.
```suggestion
    pybind11::dict getParamsPython(std::string type_name)
```

2025-01-07 18:48 UTC, mphoward commented on src/HarmonicBarrierGPU.cc
> +    this->m_autotuners.push_back(m_tuner);
Since this is not a derived class template, `this->` is not necessary here
```suggestion
    m_tuner.reset(new Autotuner<1>({AutotunerBase::makeBlockSizeRange(m_exec_conf)},
                                  m_exec_conf,
                                   "harmonic_barrier"));
   m_autotuners.push_back(m_tuner);
```

2025-01-07 18:48 UTC, mphoward commented on src/PlanarHarmonicBarrier.cc
> +    HarmonicBarrier::computeForces(timestep);
I don't think any of the parent methods actually do anything, so there is no need to invoke this here.
```suggestion
```

2025-01-07 18:48 UTC, mphoward commented on src/PlanarHarmonicBarrierGPU.cc
> +    HarmonicBarrierGPU::computeForces(timestep);
Same here
```suggestion
```

2025-01-07 18:48 UTC, mphoward commented on src/PlanarHarmonicBarrierGPU.cuh
> +cudaError_t compute_harmonic_force(Scalar4* d_force,
This function and the corresponding kernel should be renamed something more descriptive & specific to the class:
```suggestion
cudaError_t compute_force_planar_harmonic_barrier(Scalar4* d_force,
```

2025-01-07 18:48 UTC, mphoward commented on src/external.py
> +class HarmonicBarrier(force.Force):
You should make these separate classes that mirror the C++ side (`PlanarHarmonicBarrier` and `SphericalHarmonicBarrier`). They can both derive from a common `HarmonicBarrier` class though! You might follow a pattern like I did here:
https://github.com/mphowardlab/azplugins/blob/fb0ac2fe6cb894e8a437e934f8197897f3d6ad49/src/compute.py#L17

2025-01-07 18:48 UTC, mphoward commented on src/external.py
> +#    _cpp_class_name = "PlanarHarmonicBarrier"
These are not needed in our own plugin. Specify the module explicitly when you return the class name
```suggestion
```

2025-01-15 16:21 UTC, kkritikak commented
Thanks for the feedback! 🙌
I’ve addressed most of the comments by removing the cutoff and g parameters and also improved `external.py`.  have also added a new pytest for external.py. Let me know if there’s anything else to adjust. Could you please have a look whenever you have time!

2025-01-15 16:22 UTC, kkritikak commented on src/PlanarHarmonicBarrier.cc
> +    HarmonicBarrier::computeForces(timestep);
Thank you for pointing that out! I realized the parent methods actually throw a [warning](https://github.com/mphowardlab/azplugins/blob/v0.11.0/azplugins/ImplicitEvaporator.cc#L41) about the virial contributions, so I thought it might be better to keep it for now. That said, I’m not entirely sure about it—please let me know your thoughts, and I’m happy to remove it if needed!

2025-01-15 16:26 UTC, mphoward commented on src/PlanarHarmonicBarrier.cc
> +    HarmonicBarrier::computeForces(timestep);
You are correct, I missed that! Please leave these calls in.

2025-01-16 14:37 UTC, mphoward requested changes
Thank you Kritika! I have some points that still need to be addressed, but overall this looks great and is close to merging. Please let me know if you have any questions.

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        near an interface in planar geometry..
The first line of a docstring should be a short description.
```suggestion
    r"""Planar harmonic barrier normal to *z*.
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        interface (`hoomd.variant`) : `z` position of the interface
Backticks are used for cross referencing. The type should also be variant_like.
```suggestion
        interface (`hoomd.variant.variant_like`) : *z* position of the interface
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +    and have following form:
```suggestion
    `PlanarHarmonicBarrier` apply a purely harmonic potential in planar geometry
    with a normal in the :math:`+z` direction:
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        \end{eqnarray*}
I don't think equation array is needed, but you do want to use cases to make a piecewise function. Also, use the real coordinates now that we have specialized documentation:
```suggestion
        U(z) = \begin{cases}
         0 & z \le H \\
         \dfrac{\kappa}{2} (z-H)^2 & z > H
         \end{cases}
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +    (:math:`\kappa` is a proxy for the surface tension).
```suggestion
    Here, the interface is located at height *H*, which may change with time.
    `interface` specifies the nominal *H*, which may then be modified
    per-particle-type by adding an ``offset``. :math:`\kappa` is a spring
    constant setting the strength of the interface, similar to a surface tension.
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        evap.params['B'] = dict(k=50.0*2*2, offset=0.0)
```suggestion
        evap = hoomd.azplugins.external.PlanarHarmonicBarrier(interface=interf)
        evap.params['S'] = dict(k=50.0, offset=0.0)
        evap.params['B'] = dict(k=50.0*2**2, offset=0.0)
```
Please also add a short description of what this example is implementing.

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        [``particle_type``], `dict`]
This should be removed since it is common to the base class.

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        pressure (tensor) is not being logged or the pressure is not of interest.
Move this warning to the base class.

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +        super().__init__(interface=interface, geometry="film")
You are just going to call the parent constructor after you make the fixes above, so this can just be pass.
```suggestion
    pass
```

2025-01-16 14:37 UTC, mphoward commented on src/external.py
> +class SphericalHarmonicBarrier(HarmonicBarrier):
Apply similar changes as for the planar harmonic class here.

2025-01-16 14:37 UTC, mphoward commented on src/pytest/test_external.py
> +    energies = barrier.energies
These attributes are only valid on the root rank in MPI simulations. Please shift these inside a check on `sim.device.communicator.rank`

2025-01-16 14:37 UTC, mphoward commented on src/pytest/test_external.py
> +    assert numpy.isclose(forces[0][2], 0.0, atol=1e-4)
You can use `assert_allclose` to check multiple values at once, like:
```suggestion
    assert numpy.testing.assert_allclose(forces[0], [0, 0, 0], atol=1e-4)
```

2025-01-16 14:37 UTC, mphoward commented on src/pytest/test_external.py
> +    barrier = cls(interface=custom_variant_fixture)
Since this is a test for a specific class, you don't need to parametrize the test:
```suggestion
def test_spherical_harmonic_barrier(
    simulation_factory, cls, integrator, snap, custom_variant_fixture
):
    sim = simulation_factory(snap)
    sim.operations.integrator = integrator

    barrier = hoomd.azplugins.external.SphericalHarmonicBarrier(interface=custom_variant_fixture)
```

2025-01-16 14:37 UTC, mphoward commented on src/pytest/test_external.py
> +from hoomd.azplugins import external
I prefer not to use from imports in unittests because it lets us check that we have internally imported modules as we intend the user to be able to use them.
```suggestion
import hoomd.azplugins
```

2025-01-21 19:31 UTC, kkritikak commented
Thanks! I’ve addressed most of the comments. Please let me know if there’s anything else which can be improved.

2025-01-21 19:56 UTC, mphoward requested changes
Thanks Kritika! There are still some issues with  the  Python documentation. Can you please carefully go through these and make sure you have implemented everything that is needed? Especially keep an eye on the sphere class, since I think the changes for the planar geometry were not propagated there.

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +        pressure (tensor) is not being logged or the pressure is not of interest.
```suggestion
        Virial calculation has not been implemented for this external field.
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +        evap.params['B'] = dict(k=50.0*2*2, offset=0.0)
```suggestion
        evap.params['S'] = dict(k=50.0, offset=-0.5)
        # big particle is twice as large (diameter 2.0), so coefficients are scaled
        evap.params['B'] = dict(k=50.0*2*2, offset=-1.0)
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    with a normal in the :math:`+z` direction:
```suggestion
    `PlanarHarmonicBarrier` applies a purely harmonic potential in a planar
    geometry with a normal in the :math:`z` direction. Particles are pushed
    in the :math:`-z` direction when they are above the `interface`:
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    .. py:attribute:: params
Interface also needs to be documented as an attribute.

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +        interface (`hoomd.variant.variant_like`): position of the interface
```suggestion
        interface (`hoomd.variant.variant_like`): Position of the interface
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    r"""Applies harmonic barrier.
```suggestion
    r"""Repulsive barrier implemented as a harmonic potential.
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    ``interface`` specifies the nominal *H*, which may then be modified
```suggestion
    `interface` specifies the nominal *H*, which may then be modified
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +        interface (`hoomd.variant.variant_like`) : Radius of spherical interface.
```suggestion
        interface (`hoomd.variant.variant_like`) : Radius of sphere.
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    and has the following form:
```suggestion
    `SphericalHarmonicBarrier` applies a purely harmonic potential to particles
    outside the radius of a sphere, acting to push them inward:
```

2025-01-21 19:56 UTC, mphoward commented on src/external.py
> +    .. math::
Fix the documentation from here to the end to make it mirror the planar geometry documentation. Those changes were not applied here.

2025-01-22 12:13 UTC, kkritikak commented on src/external.py
> +    ``interface`` specifies the nominal *H*, which may then be modified
I wanted to inform you that a warning is being raised during documentation compilation because there is no existing cross-reference for interface. As a result, Sphinx throws the following warning, causing the ReadTheDocs tests to fail:
`hoomd/azplugins/external.py:docstring of hoomd.azplugins.external.PlanarHarmonicBarrier:6: WARNING: 'any' reference target not found: interface [ref.any]`
If I enclose the interface in double backticks (interface) it doesn't cause any problem. Is there a better way to resolve this issue?

2025-01-22 22:12 UTC, mphoward commented on src/external.py
> +    ``interface`` specifies the nominal *H*, which may then be modified
Oh, yes, that is because that attribute is in the base class, I think, and is not inherited in the documentation. Yes, it is OK to use the double backticks to fix that warning.

2025-01-24 02:14 UTC, mphoward approved these changes
Thank you for your work on this! I refactored your code to use a template class to reduce duplication and number of files we have to maintain. I also fixed some issues with the documentation and a deadlock when the unit tests were run with MPI. I will batch commit the small changes I marked here during review, and merge after the unit tests pass. I appreciate you taking care of this!

2025-01-24 02:14 UTC, mphoward commented on src/PlanarBarrierEvaluator.h
> +        const Scalar f = -k * dy;               // z component of force
```suggestion
        const Scalar f = -k * dy;               // y component of force
```

2025-01-24 02:14 UTC, mphoward commented on doc/module-azplugins-external.rst
> +    :synopsis: External barrier.
```suggestion
    :synopsis: External potentials.
```

2025-01-24 02:14 UTC, mphoward commented on src/SphericalBarrierEvaluator.h
> +    Scalar m_R; // Radius of sphere
```suggestion
    Scalar m_R; //<! Radius of sphere
```

2025-01-24 02:14 UTC, mphoward commented on src/PlanarBarrierEvaluator.h
> +    Scalar m_H; // y position of interface
```suggestion
    Scalar m_H; //<! y position of interface
```

2025-01-24 02:14 UTC, mphoward commented on src/external.py
> +"""External harmonic potentials."""
```suggestion
"""External potentials."""
```

2025-01-24 02:14 UTC, mphoward commented on src/external.py
> +        Location of the barrier. The meaning of this position is interpreted
```suggestion
        Location of the barrier. The meaning of this location is interpreted
```

2025-01-24 02:14 UTC, mphoward commented on src/external.py
> +    in the :math:`-y` direction when they are above the ``location``:
```suggestion
    `PlanarHarmonicBarrier` applies a purely repulsive harmonic potential
    in a planar geometry with a normal in the :math:`y` direction. Particles
    are pushed in the :math:`-y` direction when they are above the
    ``location``:
```

2025-01-24 02:14 UTC, mphoward commented on src/external.py
> +    outside the radius of a sphere, acting to push them inward:
```suggestion
    `SphericalHarmonicBarrier` applies a purely repulsive harmonic potential to
    particles outside the radius of a sphere, acting to push them inward:
```

2025-01-24 03:03 UTC, merged